package pgrid.service.corba.simulation;


/**
 * pgrid/service/corba/simulation/SimulationHandlePOA.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Wednesday, April 18, 2012 12:20:15 PM EEST
 */

public abstract class SimulationHandlePOA extends org.omg.PortableServer.Servant
        implements pgrid.service.corba.simulation.SimulationHandleOperations, org.omg.CORBA.portable.InvokeHandler {

    // Constructors

    private static java.util.Hashtable _methods = new java.util.Hashtable();

    static {
        _methods.put("getInfo", new java.lang.Integer(0));
        _methods.put("die", new java.lang.Integer(1));
        _methods.put("terminateSimulation", new java.lang.Integer(2));
    }

    public org.omg.CORBA.portable.OutputStream _invoke(String $method,
                                                       org.omg.CORBA.portable.InputStream in,
                                                       org.omg.CORBA.portable.ResponseHandler $rh) {
        org.omg.CORBA.portable.OutputStream out = null;
        java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
        if (__method == null)
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

        switch (__method.intValue()) {
            case 0:  // pgrid/service/corba/simulation/SimulationHandle/getInfo
            {
                pgrid.service.corba.PeerReference $result = null;
                $result = this.getInfo();
                out = $rh.createReply();
                pgrid.service.corba.PeerReferenceHelper.write(out, $result);
                break;
            }

            case 1:  // pgrid/service/corba/simulation/SimulationHandle/die
            {
                this.die();
                out = $rh.createReply();
                break;
            }

            case 2:  // pgrid/service/corba/simulation/SimulationHandle/terminateSimulation
            {
                this.terminateSimulation();
                out = $rh.createReply();
                break;
            }

            default:
                throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        return out;
    } // _invoke

    // Type-specific CORBA::Object operations
    private static String[] __ids = {
            "IDL:pgrid/service/corba/simulation/SimulationHandle:1.0"};

    public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId) {
        return (String[]) __ids.clone();
    }

    public SimulationHandle _this() {
        return SimulationHandleHelper.narrow(
                super._this_object());
    }

    public SimulationHandle _this(org.omg.CORBA.ORB orb) {
        return SimulationHandleHelper.narrow(
                super._this_object(orb));
    }


} // class SimulationHandlePOA
