package pgrid.service.corba.simulation;


/**
 * pgrid/service/corba/simulation/SimulationHandle.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Wednesday, April 18, 2012 12:20:15 PM EEST
 */

public interface SimulationHandle extends SimulationHandleOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface SimulationHandle
