package pgrid.service.corba.simulation;


/**
 * pgrid/service/spi/corba/simulation/SimulationHandle.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Saturday, January 21, 2012 1:52:15 AM EET
 */

public interface SimulationHandle extends SimulationHandleOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface SimulationHandle
