package pgrid.service.corba.simulation;


/**
 * pgrid/service/corba/simulation/SimulationHandleOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Saturday, January 21, 2012 3:01:22 AM EET
 */

public interface SimulationHandleOperations {
    void die();

    void terminateSimulation();
} // interface SimulationHandleOperations
