package pgrid.service.corba.simulation;

/**
 * pgrid/service/spi/corba/simulation/SimulationHandleHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Saturday, January 21, 2012 1:52:15 AM EET
 */

public final class SimulationHandleHolder implements org.omg.CORBA.portable.Streamable {
    public pgrid.service.corba.simulation.SimulationHandle value = null;

    public SimulationHandleHolder() {
    }

    public SimulationHandleHolder(pgrid.service.corba.simulation.SimulationHandle initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = pgrid.service.corba.simulation.SimulationHandleHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        pgrid.service.corba.simulation.SimulationHandleHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return pgrid.service.corba.simulation.SimulationHandleHelper.type();
    }

}
