/*
 * This file is part of the pgrid project.
 *
 * Copyright (c) 2012. Vourlakis Nikolas. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package pgrid.service.corba.exchange;


/**
 * pgrid/service/corba/exchange/ExchangeHandlePOA.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Tuesday, January 24, 2012 7:07:45 PM EET
 */

public abstract class ExchangeHandlePOA extends org.omg.PortableServer.Servant
        implements pgrid.service.corba.exchange.ExchangeHandleOperations, org.omg.CORBA.portable.InvokeHandler {

    // Constructors

    private static java.util.Hashtable _methods = new java.util.Hashtable();

    static {
        _methods.put("_get_routingTable", new java.lang.Integer(0));
        _methods.put("exchange", new java.lang.Integer(1));
    }

    public org.omg.CORBA.portable.OutputStream _invoke(String $method,
                                                       org.omg.CORBA.portable.InputStream in,
                                                       org.omg.CORBA.portable.ResponseHandler $rh) {
        org.omg.CORBA.portable.OutputStream out = null;
        java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
        if (__method == null)
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

        switch (__method.intValue()) {
            case 0:  // pgrid/service/corba/exchange/ExchangeHandle/_get_routingTable
            {
                pgrid.service.corba.CorbaRoutingTable $result = null;
                $result = this.routingTable();
                out = $rh.createReply();
                pgrid.service.corba.CorbaRoutingTableHelper.write(out, $result);
                break;
            }

            case 1:  // pgrid/service/corba/exchange/ExchangeHandle/exchange
            {
                pgrid.service.corba.CorbaRoutingTable routingTable = pgrid.service.corba.CorbaRoutingTableHelper.read(in);
                this.exchange(routingTable);
                out = $rh.createReply();
                break;
            }

            default:
                throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        return out;
    } // _invoke

    // Type-specific CORBA::Object operations
    private static String[] __ids = {
            "IDL:pgrid/service/corba/exchange/ExchangeHandle:1.0"};

    public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId) {
        return (String[]) __ids.clone();
    }

    public ExchangeHandle _this() {
        return ExchangeHandleHelper.narrow(
                super._this_object());
    }

    public ExchangeHandle _this(org.omg.CORBA.ORB orb) {
        return ExchangeHandleHelper.narrow(
                super._this_object(orb));
    }


} // class ExchangeHandlePOA
