package pgrid.service.corba.exchange;


import pgrid.service.corba.CorbaRoutingTable;

/**
 * pgrid/service/spi/corba/exchange/ExchangeHandleOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Saturday, January 21, 2012 1:52:15 AM EET
 */

public interface ExchangeHandleOperations {
    CorbaRoutingTable routingTable();

    void exchange(CorbaRoutingTable routingTable);
} // interface ExchangeHandleOperations
