package pgrid.service.corba.exchange;


/**
* pgrid/service/corba/exchange/ExchangeHandle.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/pgrid_corba.idl
* Wednesday, April 18, 2012 12:20:15 PM EEST
*/

public interface ExchangeHandle extends ExchangeHandleOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ExchangeHandle
