package pgrid.service.corba.exchange;


/**
 * pgrid/service/corba/exchange/ExchangeHandleOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Wednesday, April 18, 2012 12:20:15 PM EEST
 */

public interface ExchangeHandleOperations {
    pgrid.service.corba.CorbaRoutingTable routingTable();

    void exchange(pgrid.service.corba.CorbaRoutingTable routingTable);
} // interface ExchangeHandleOperations
