package pgrid.service.corba.exchange;

/**
 * pgrid/service/spi/corba/exchange/ExchangeHandleHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Saturday, January 21, 2012 1:52:15 AM EET
 */

public final class ExchangeHandleHolder implements org.omg.CORBA.portable.Streamable {
    public pgrid.service.corba.exchange.ExchangeHandle value = null;

    public ExchangeHandleHolder() {
    }

    public ExchangeHandleHolder(pgrid.service.corba.exchange.ExchangeHandle initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = pgrid.service.corba.exchange.ExchangeHandleHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        pgrid.service.corba.exchange.ExchangeHandleHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return pgrid.service.corba.exchange.ExchangeHandleHelper.type();
    }

}
