package pgrid.service.corba.exchange;


/**
* pgrid/service/corba/exchange/ExchangeHandleHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/pgrid_corba.idl
* Wednesday, April 18, 2012 12:20:15 PM EEST
*/

abstract public class ExchangeHandleHelper
{
  private static String  _id = "IDL:pgrid/service/corba/exchange/ExchangeHandle:1.0";

  public static void insert (org.omg.CORBA.Any a, pgrid.service.corba.exchange.ExchangeHandle that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static pgrid.service.corba.exchange.ExchangeHandle extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (pgrid.service.corba.exchange.ExchangeHandleHelper.id (), "ExchangeHandle");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static pgrid.service.corba.exchange.ExchangeHandle read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ExchangeHandleStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, pgrid.service.corba.exchange.ExchangeHandle value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static pgrid.service.corba.exchange.ExchangeHandle narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof pgrid.service.corba.exchange.ExchangeHandle)
      return (pgrid.service.corba.exchange.ExchangeHandle)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      pgrid.service.corba.exchange._ExchangeHandleStub stub = new pgrid.service.corba.exchange._ExchangeHandleStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static pgrid.service.corba.exchange.ExchangeHandle unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof pgrid.service.corba.exchange.ExchangeHandle)
      return (pgrid.service.corba.exchange.ExchangeHandle)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      pgrid.service.corba.exchange._ExchangeHandleStub stub = new pgrid.service.corba.exchange._ExchangeHandleStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
