package pgrid.service.corba;


/**
 * pgrid/service/spi/corba/CorbaRoutingTable.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Saturday, January 21, 2012 1:52:15 AM EET
 */

public final class CorbaRoutingTable implements org.omg.CORBA.portable.IDLEntity {
    public PeerReference refs[][] = null;
    public PeerReference peer = null;

    public CorbaRoutingTable() {
    } // ctor

    public CorbaRoutingTable(PeerReference[][] _refs, PeerReference _peer) {
        refs = _refs;
        peer = _peer;
    } // ctor

} // class CorbaRoutingTable
