package pgrid.service.corba;

/**
 * pgrid/service/spi/corba/CorbaRoutingTableHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Saturday, January 21, 2012 1:52:15 AM EET
 */

public final class CorbaRoutingTableHolder implements org.omg.CORBA.portable.Streamable {
    public CorbaRoutingTable value = null;

    public CorbaRoutingTableHolder() {
    }

    public CorbaRoutingTableHolder(CorbaRoutingTable initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = CorbaRoutingTableHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        CorbaRoutingTableHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return CorbaRoutingTableHelper.type();
    }

}
