package pgrid.service.corba;

/**
* pgrid/service/corba/PeerReferenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/pgrid_corba.idl
* Wednesday, April 18, 2012 12:20:15 PM EEST
*/

public final class PeerReferenceHolder implements org.omg.CORBA.portable.Streamable
{
  public pgrid.service.corba.PeerReference value = null;

  public PeerReferenceHolder ()
  {
  }

  public PeerReferenceHolder (pgrid.service.corba.PeerReference initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pgrid.service.corba.PeerReferenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pgrid.service.corba.PeerReferenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pgrid.service.corba.PeerReferenceHelper.type ();
  }

}
