package pgrid.service.corba;

/**
 * pgrid/service/spi/corba/PeerReferenceHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Saturday, January 21, 2012 1:52:15 AM EET
 */

public final class PeerReferenceHolder implements org.omg.CORBA.portable.Streamable {
    public PeerReference value = null;

    public PeerReferenceHolder() {
    }

    public PeerReferenceHolder(PeerReference initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = PeerReferenceHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        PeerReferenceHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return PeerReferenceHelper.type();
    }

}
