package pgrid.service.corba;


/**
 * pgrid/service/corba/ReferencesHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Wednesday, April 18, 2012 12:20:15 PM EEST
 */

public final class ReferencesHolder implements org.omg.CORBA.portable.Streamable {
    public pgrid.service.corba.PeerReference value[][] = null;

    public ReferencesHolder() {
    }

    public ReferencesHolder(pgrid.service.corba.PeerReference[][] initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = pgrid.service.corba.ReferencesHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        pgrid.service.corba.ReferencesHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return pgrid.service.corba.ReferencesHelper.type();
    }

}
