package pgrid.service.corba;


/**
 * pgrid/service/spi/corba/StringArrayHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Saturday, January 21, 2012 1:52:15 AM EET
 */

public final class StringArrayHolder implements org.omg.CORBA.portable.Streamable {
    public String value[] = null;

    public StringArrayHolder() {
    }

    public StringArrayHolder(String[] initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = StringArrayHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        StringArrayHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return StringArrayHelper.type();
    }

}
