package pgrid.service.corba;


/**
 * pgrid/service/corba/StringArrayHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/pgrid_corba.idl
 * Wednesday, April 18, 2012 12:20:15 PM EEST
 */

public final class StringArrayHolder implements org.omg.CORBA.portable.Streamable {
    public String value[] = null;

    public StringArrayHolder() {
    }

    public StringArrayHolder(String[] initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = pgrid.service.corba.StringArrayHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        pgrid.service.corba.StringArrayHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return pgrid.service.corba.StringArrayHelper.type();
    }

}
