package pgrid.service.spi.corba.simulation;


/**
* pgrid/service/spi/corba/simulation/SimulationHandleHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/pgrid_corba.idl
* Thursday, January 19, 2012 10:19:41 PM EET
*/

abstract public class SimulationHandleHelper
{
  private static String  _id = "IDL:pgrid/service/spi/corba/simulation/SimulationHandle:1.0";

  public static void insert (org.omg.CORBA.Any a, pgrid.service.spi.corba.simulation.SimulationHandle that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static pgrid.service.spi.corba.simulation.SimulationHandle extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (pgrid.service.spi.corba.simulation.SimulationHandleHelper.id (), "SimulationHandle");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static pgrid.service.spi.corba.simulation.SimulationHandle read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SimulationHandleStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, pgrid.service.spi.corba.simulation.SimulationHandle value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static pgrid.service.spi.corba.simulation.SimulationHandle narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof pgrid.service.spi.corba.simulation.SimulationHandle)
      return (pgrid.service.spi.corba.simulation.SimulationHandle)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      pgrid.service.spi.corba.simulation._SimulationHandleStub stub = new pgrid.service.spi.corba.simulation._SimulationHandleStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static pgrid.service.spi.corba.simulation.SimulationHandle unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof pgrid.service.spi.corba.simulation.SimulationHandle)
      return (pgrid.service.spi.corba.simulation.SimulationHandle)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      pgrid.service.spi.corba.simulation._SimulationHandleStub stub = new pgrid.service.spi.corba.simulation._SimulationHandleStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
