package pgrid.service.spi.corba.simulation;

/**
* pgrid/service/spi/corba/simulation/SimulationHandleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/pgrid_corba.idl
* Thursday, January 19, 2012 10:19:41 PM EET
*/

public final class SimulationHandleHolder implements org.omg.CORBA.portable.Streamable
{
  public pgrid.service.spi.corba.simulation.SimulationHandle value = null;

  public SimulationHandleHolder ()
  {
  }

  public SimulationHandleHolder (pgrid.service.spi.corba.simulation.SimulationHandle initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pgrid.service.spi.corba.simulation.SimulationHandleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pgrid.service.spi.corba.simulation.SimulationHandleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pgrid.service.spi.corba.simulation.SimulationHandleHelper.type ();
  }

}
