package pgrid.service.spi.corba.simulation;


/**
* pgrid/service/spi/corba/simulation/SimulationHandleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/pgrid_corba.idl
* Thursday, January 19, 2012 10:19:41 PM EET
*/

public interface SimulationHandleOperations 
{
  void die ();
  void terminateSimulation ();
} // interface SimulationHandleOperations
