package pgrid.service.corba.fileTransfer.TransferHandlePackage;


/**
* pgrid/service/corba/fileTransfer/TransferHandlePackage/DataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/demo_transfer_corba.idl
* Τρίτη, 9 Οκτώβριος 2012 12:55:40 πμ EEST
*/

public final class DataHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public DataHolder ()
  {
  }

  public DataHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pgrid.service.corba.fileTransfer.TransferHandlePackage.DataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pgrid.service.corba.fileTransfer.TransferHandlePackage.DataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pgrid.service.corba.fileTransfer.TransferHandlePackage.DataHelper.type ();
  }

}
