package pgrid.service.spi.corba;


/**
* pgrid/service/spi/corba/CorbaRoutingTable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/pgrid_corba.idl
* Thursday, January 19, 2012 9:18:13 PM EET
*/

public final class CorbaRoutingTable implements org.omg.CORBA.portable.IDLEntity
{
  public pgrid.service.spi.corba.PeerReference refs[][] = null;
  public pgrid.service.spi.corba.PeerReference peer = null;

  public CorbaRoutingTable ()
  {
  } // ctor

  public CorbaRoutingTable (pgrid.service.spi.corba.PeerReference[][] _refs, pgrid.service.spi.corba.PeerReference _peer)
  {
    refs = _refs;
    peer = _peer;
  } // ctor

} // class CorbaRoutingTable
