/*
 * This file (pgrid.service.spi.corba.CorbaRoutingTable) is part of the libpgrid project.
 *
 * Copyright (c) 2011. Vourlakis Nikolas. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package pgrid.service.spi.corba;


/**
* pgrid/service/spi/corba/CorbaRoutingTable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/user/Desktop/DIPLOMATIKH_NIKOLA/libpgrid/resources/pgrid_corba.idl
*/

public final class CorbaRoutingTable implements org.omg.CORBA.portable.IDLEntity
{
  public pgrid.service.spi.corba.PeerReference refs[][] = null;
  public pgrid.service.spi.corba.PeerReference peer = null;

  public CorbaRoutingTable ()
  {
  } // ctor

  public CorbaRoutingTable (pgrid.service.spi.corba.PeerReference[][] _refs, pgrid.service.spi.corba.PeerReference _peer)
  {
    refs = _refs;
    peer = _peer;
  } // ctor

} // class CorbaRoutingTable
