package pgrid.service.spi.corba;


/**
* pgrid/service/spi/corba/ExchangeHandle.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/user/Desktop/DIPLOMATIKH_NIKOLA/libpgrid/resources/pgrid_corba.idl
*/

public interface ExchangeHandle extends ExchangeHandleOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ExchangeHandle
