package pgrid.service.spi.corba;


/**
* pgrid/service/spi/corba/ExchangeHandleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/user/Desktop/DIPLOMATIKH_NIKOLA/libpgrid/resources/pgrid_corba.idl
*/

public interface ExchangeHandleOperations 
{
  pgrid.service.spi.corba.RoutingTable routingTable ();
  void exchange (pgrid.service.spi.corba.RoutingTable routingTable);
} // interface ExchangeHandleOperations
