package pgrid.service.spi.corba;

/**
 * pgrid/service/spi/corba/ExchangeHandleHolder.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from C:/Users/user/Desktop/DIPLOMATIKH_NIKOLA/libpgrid/resources/pgrid_corba.idl
 */

public final class ExchangeHandleHolder implements org.omg.CORBA.portable.Streamable {
    public pgrid.service.spi.corba.ExchangeHandle value = null;

    public ExchangeHandleHolder() {
    }

    public ExchangeHandleHolder(pgrid.service.spi.corba.ExchangeHandle initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = pgrid.service.spi.corba.ExchangeHandleHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        pgrid.service.spi.corba.ExchangeHandleHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return pgrid.service.spi.corba.ExchangeHandleHelper.type();
    }

}
