package pgrid.service.spi.corba;


/**
* pgrid/service/spi/corba/PeerArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/pgrid_corba.idl
* Thursday, January 19, 2012 10:19:41 PM EET
*/

public final class PeerArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public pgrid.service.spi.corba.PeerReference value[] = null;

  public PeerArrayHolder ()
  {
  }

  public PeerArrayHolder (pgrid.service.spi.corba.PeerReference[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pgrid.service.spi.corba.PeerArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pgrid.service.spi.corba.PeerArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pgrid.service.spi.corba.PeerArrayHelper.type ();
  }

}
