package pgrid.service.spi.corba;

/**
* pgrid/service/spi/corba/RoutingTableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/user/Desktop/DIPLOMATIKH_NIKOLA/libpgrid/resources/pgrid_corba.idl
*/

public final class RoutingTableHolder implements org.omg.CORBA.portable.Streamable
{
  public pgrid.service.spi.corba.RoutingTable value = null;

  public RoutingTableHolder ()
  {
  }

  public RoutingTableHolder (pgrid.service.spi.corba.RoutingTable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pgrid.service.spi.corba.RoutingTableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pgrid.service.spi.corba.RoutingTableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pgrid.service.spi.corba.RoutingTableHelper.type ();
  }

}
