package pgrid.service.corba.fileTransfer;


/**
 * pgrid/service/corba/fileTransfer/_TransferHandleStub.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/demo_transfer_corba.idl
 * Τρίτη, 9 Οκτώβριος 2012 12:55:40 πμ EEST
 */

public class _TransferHandleStub extends org.omg.CORBA.portable.ObjectImpl implements pgrid.service.corba.fileTransfer.TransferHandle {

    public byte[] transfer(String fileName) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("transfer", true);
            $out.write_string(fileName);
            $in = _invoke($out);
            byte $result[] = pgrid.service.corba.fileTransfer.TransferHandlePackage.DataHelper.read($in);
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return transfer(fileName);
        } finally {
            _releaseReply($in);
        }
    } // transfer

    // Type-specific CORBA::Object operations
    private static String[] __ids = {
            "IDL:pgrid/service/corba/fileTransfer/TransferHandle:1.0"};

    public String[] _ids() {
        return (String[]) __ids.clone();
    }

    private void readObject(java.io.ObjectInputStream s) throws java.io.IOException {
        String str = s.readUTF();
        String[] args = null;
        java.util.Properties props = null;
        org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init(args, props).string_to_object(str);
        org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
        _set_delegate(delegate);
    }

    private void writeObject(java.io.ObjectOutputStream s) throws java.io.IOException {
        String[] args = null;
        java.util.Properties props = null;
        String str = org.omg.CORBA.ORB.init(args, props).object_to_string(this);
        s.writeUTF(str);
    }
} // class _TransferHandleStub
