package pgrid.service.corba.fileTransfer;


/**
* pgrid/service/corba/fileTransfer/TransferHandleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/demo_transfer_corba.idl
* Τρίτη, 9 Οκτώβριος 2012 12:55:40 πμ EEST
*/

public interface TransferHandleOperations 
{
  byte[] transfer (String fileName);
} // interface TransferHandleOperations
