package pgrid.service.corba.fileTransfer;


/**
* pgrid/service/corba/fileTransfer/TransferHandlePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/demo_transfer_corba.idl
* Τρίτη, 9 Οκτώβριος 2012 12:55:40 πμ EEST
*/

public abstract class TransferHandlePOA extends org.omg.PortableServer.Servant
 implements pgrid.service.corba.fileTransfer.TransferHandleOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("transfer", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // pgrid/service/corba/fileTransfer/TransferHandle/transfer
       {
         String fileName = in.read_string ();
         byte $result[] = null;
         $result = this.transfer (fileName);
         out = $rh.createReply();
         pgrid.service.corba.fileTransfer.TransferHandlePackage.DataHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:pgrid/service/corba/fileTransfer/TransferHandle:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TransferHandle _this() 
  {
    return TransferHandleHelper.narrow(
    super._this_object());
  }

  public TransferHandle _this(org.omg.CORBA.ORB orb) 
  {
    return TransferHandleHelper.narrow(
    super._this_object(orb));
  }


} // class TransferHandlePOA
