package pgrid.service.corba.fileTransfer;


/**
 * pgrid/service/corba/fileTransfer/TransferHandleHelper.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/demo_transfer_corba.idl
 * Τρίτη, 9 Οκτώβριος 2012 12:55:40 πμ EEST
 */

abstract public class TransferHandleHelper {
    private static String _id = "IDL:pgrid/service/corba/fileTransfer/TransferHandle:1.0";

    public static void insert(org.omg.CORBA.Any a, pgrid.service.corba.fileTransfer.TransferHandle that) {
        org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
        a.type(type());
        write(out, that);
        a.read_value(out.create_input_stream(), type());
    }

    public static pgrid.service.corba.fileTransfer.TransferHandle extract(org.omg.CORBA.Any a) {
        return read(a.create_input_stream());
    }

    private static org.omg.CORBA.TypeCode __typeCode = null;

    synchronized public static org.omg.CORBA.TypeCode type() {
        if (__typeCode == null) {
            __typeCode = org.omg.CORBA.ORB.init().create_interface_tc(pgrid.service.corba.fileTransfer.TransferHandleHelper.id(), "TransferHandle");
        }
        return __typeCode;
    }

    public static String id() {
        return _id;
    }

    public static pgrid.service.corba.fileTransfer.TransferHandle read(org.omg.CORBA.portable.InputStream istream) {
        return narrow(istream.read_Object(_TransferHandleStub.class));
    }

    public static void write(org.omg.CORBA.portable.OutputStream ostream, pgrid.service.corba.fileTransfer.TransferHandle value) {
        ostream.write_Object((org.omg.CORBA.Object) value);
    }

    public static pgrid.service.corba.fileTransfer.TransferHandle narrow(org.omg.CORBA.Object obj) {
        if (obj == null)
            return null;
        else if (obj instanceof pgrid.service.corba.fileTransfer.TransferHandle)
            return (pgrid.service.corba.fileTransfer.TransferHandle) obj;
        else if (!obj._is_a(id()))
            throw new org.omg.CORBA.BAD_PARAM();
        else {
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
            pgrid.service.corba.fileTransfer._TransferHandleStub stub = new pgrid.service.corba.fileTransfer._TransferHandleStub();
            stub._set_delegate(delegate);
            return stub;
        }
    }

    public static pgrid.service.corba.fileTransfer.TransferHandle unchecked_narrow(org.omg.CORBA.Object obj) {
        if (obj == null)
            return null;
        else if (obj instanceof pgrid.service.corba.fileTransfer.TransferHandle)
            return (pgrid.service.corba.fileTransfer.TransferHandle) obj;
        else {
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
            pgrid.service.corba.fileTransfer._TransferHandleStub stub = new pgrid.service.corba.fileTransfer._TransferHandleStub();
            stub._set_delegate(delegate);
            return stub;
        }
    }

}
