package pgrid.service.spi.corba.exchange;


/**
* pgrid/service/spi/corba/exchange/_ExchangeHandleStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/pgrid_corba.idl
* Thursday, January 19, 2012 9:18:13 PM EET
*/

public class _ExchangeHandleStub extends org.omg.CORBA.portable.ObjectImpl implements pgrid.service.spi.corba.exchange.ExchangeHandle
{

  public pgrid.service.spi.corba.CorbaRoutingTable routingTable ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_routingTable", true);
                $in = _invoke ($out);
                pgrid.service.spi.corba.CorbaRoutingTable $result = pgrid.service.spi.corba.CorbaRoutingTableHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return routingTable (        );
            } finally {
                _releaseReply ($in);
            }
  } // routingTable

  public void exchange (pgrid.service.spi.corba.CorbaRoutingTable routingTable)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("exchange", true);
                pgrid.service.spi.corba.CorbaRoutingTableHelper.write ($out, routingTable);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                exchange (routingTable        );
            } finally {
                _releaseReply ($in);
            }
  } // exchange

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:pgrid/service/spi/corba/exchange/ExchangeHandle:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _ExchangeHandleStub
