package pgrid.service.spi.corba.exchange;


/**
* pgrid/service/spi/corba/exchange/ExchangeHandleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/pgrid_corba.idl
* Thursday, January 19, 2012 9:18:13 PM EET
*/

public interface ExchangeHandleOperations 
{
  pgrid.service.spi.corba.CorbaRoutingTable routingTable ();
  void exchange (pgrid.service.spi.corba.CorbaRoutingTable routingTable);
} // interface ExchangeHandleOperations
