package pgrid.service.spi.corba.exchange;


/**
* pgrid/service/spi/corba/exchange/ExchangeHandle.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/pgrid_corba.idl
* Thursday, January 19, 2012 9:18:13 PM EET
*/

public interface ExchangeHandle extends ExchangeHandleOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ExchangeHandle
