package pgrid.service.spi.corba.exchange;


/**
* pgrid/service/spi/corba/exchange/ExchangeHandleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/pgrid_corba.idl
* Friday, January 13, 2012 9:51:40 PM EET
*/

public interface ExchangeHandleOperations 
{
  pgrid.service.spi.corba.CorbaRoutingTable routingTable ();
  void exchange (pgrid.service.spi.corba.CorbaRoutingTable routingTable);
} // interface ExchangeHandleOperations
