package pgrid.service.spi.corba.exchange;


/**
* pgrid/service/spi/corba/exchange/ExchangeHandlePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/pgrid_corba.idl
* Thursday, January 19, 2012 10:19:41 PM EET
*/

public abstract class ExchangeHandlePOA extends org.omg.PortableServer.Servant
 implements pgrid.service.spi.corba.exchange.ExchangeHandleOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_routingTable", new java.lang.Integer (0));
    _methods.put ("exchange", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // pgrid/service/spi/corba/exchange/ExchangeHandle/_get_routingTable
       {
         pgrid.service.spi.corba.CorbaRoutingTable $result = null;
         $result = this.routingTable ();
         out = $rh.createReply();
         pgrid.service.spi.corba.CorbaRoutingTableHelper.write (out, $result);
         break;
       }

       case 1:  // pgrid/service/spi/corba/exchange/ExchangeHandle/exchange
       {
         pgrid.service.spi.corba.CorbaRoutingTable routingTable = pgrid.service.spi.corba.CorbaRoutingTableHelper.read (in);
         this.exchange (routingTable);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:pgrid/service/spi/corba/exchange/ExchangeHandle:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ExchangeHandle _this() 
  {
    return ExchangeHandleHelper.narrow(
    super._this_object());
  }

  public ExchangeHandle _this(org.omg.CORBA.ORB orb) 
  {
    return ExchangeHandleHelper.narrow(
    super._this_object(orb));
  }


} // class ExchangeHandlePOA
