package pgrid.service.corba.storage;


/**
 * pgrid/service/corba/storage/_StorageHandleStub.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/demo_storage_corba.idl
 * Παρασκευή, 5 Οκτώβριος 2012 7:51:04 μμ EEST
 */

public class _StorageHandleStub extends org.omg.CORBA.portable.ObjectImpl implements pgrid.service.corba.storage.StorageHandle {

    public pgrid.service.corba.storage.SearchResponse search(pgrid.service.corba.storage.SearchRequest request) {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request("search", true);
            pgrid.service.corba.storage.SearchRequestHelper.write($out, request);
            $in = _invoke($out);
            pgrid.service.corba.storage.SearchResponse $result = pgrid.service.corba.storage.SearchResponseHelper.read($in);
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return search(request);
        } finally {
            _releaseReply($in);
        }
    } // search

    // Type-specific CORBA::Object operations
    private static String[] __ids = {
            "IDL:pgrid/service/corba/storage/StorageHandle:1.0"};

    public String[] _ids() {
        return (String[]) __ids.clone();
    }

    private void readObject(java.io.ObjectInputStream s) throws java.io.IOException {
        String str = s.readUTF();
        String[] args = null;
        java.util.Properties props = null;
        org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init(args, props).string_to_object(str);
        org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate();
        _set_delegate(delegate);
    }

    private void writeObject(java.io.ObjectOutputStream s) throws java.io.IOException {
        String[] args = null;
        java.util.Properties props = null;
        String str = org.omg.CORBA.ORB.init(args, props).object_to_string(this);
        s.writeUTF(str);
    }
} // class _StorageHandleStub
