package pgrid.service.corba.storage;


/**
* pgrid/service/corba/storage/SearchResponse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/demo_storage_corba.idl
* Παρασκευή, 5 Οκτώβριος 2012 7:51:04 μμ EEST
*/

public final class SearchResponse implements org.omg.CORBA.portable.IDLEntity
{
  public boolean found = false;
  public pgrid.service.corba.PeerReference peer = null;

  public SearchResponse ()
  {
  } // ctor

  public SearchResponse (boolean _found, pgrid.service.corba.PeerReference _peer)
  {
    found = _found;
    peer = _peer;
  } // ctor

} // class SearchResponse
