package pgrid.service.corba.storage;


/**
 * pgrid/service/corba/storage/SearchResponseHelper.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from resources/demo_storage_corba.idl
 * Παρασκευή, 5 Οκτώβριος 2012 7:51:04 μμ EEST
 */

abstract public class SearchResponseHelper {
    private static String _id = "IDL:pgrid/service/corba/storage/SearchResponse:1.0";

    public static void insert(org.omg.CORBA.Any a, pgrid.service.corba.storage.SearchResponse that) {
        org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
        a.type(type());
        write(out, that);
        a.read_value(out.create_input_stream(), type());
    }

    public static pgrid.service.corba.storage.SearchResponse extract(org.omg.CORBA.Any a) {
        return read(a.create_input_stream());
    }

    private static org.omg.CORBA.TypeCode __typeCode = null;
    private static boolean __active = false;

    synchronized public static org.omg.CORBA.TypeCode type() {
        if (__typeCode == null) {
            synchronized (org.omg.CORBA.TypeCode.class) {
                if (__typeCode == null) {
                    if (__active) {
                        return org.omg.CORBA.ORB.init().create_recursive_tc(_id);
                    }
                    __active = true;
                    org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember[2];
                    org.omg.CORBA.TypeCode _tcOf_members0 = null;
                    _tcOf_members0 = org.omg.CORBA.ORB.init().get_primitive_tc(org.omg.CORBA.TCKind.tk_boolean);
                    _members0[0] = new org.omg.CORBA.StructMember(
                            "found",
                            _tcOf_members0,
                            null);
                    _tcOf_members0 = pgrid.service.corba.PeerReferenceHelper.type();
                    _members0[1] = new org.omg.CORBA.StructMember(
                            "peer",
                            _tcOf_members0,
                            null);
                    __typeCode = org.omg.CORBA.ORB.init().create_struct_tc(pgrid.service.corba.storage.SearchResponseHelper.id(), "SearchResponse", _members0);
                    __active = false;
                }
            }
        }
        return __typeCode;
    }

    public static String id() {
        return _id;
    }

    public static pgrid.service.corba.storage.SearchResponse read(org.omg.CORBA.portable.InputStream istream) {
        pgrid.service.corba.storage.SearchResponse value = new pgrid.service.corba.storage.SearchResponse();
        value.found = istream.read_boolean();
        value.peer = pgrid.service.corba.PeerReferenceHelper.read(istream);
        return value;
    }

    public static void write(org.omg.CORBA.portable.OutputStream ostream, pgrid.service.corba.storage.SearchResponse value) {
        ostream.write_boolean(value.found);
        pgrid.service.corba.PeerReferenceHelper.write(ostream, value.peer);
    }

}
