package pgrid.service.corba.storage;


/**
* pgrid/service/corba/storage/SearchRequest.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/demo_storage_corba.idl
* Παρασκευή, 5 Οκτώβριος 2012 7:51:04 μμ EEST
*/

public final class SearchRequest implements org.omg.CORBA.portable.IDLEntity
{
  public String key = null;
  public String filename = null;

  public SearchRequest ()
  {
  } // ctor

  public SearchRequest (String _key, String _filename)
  {
    key = _key;
    filename = _filename;
  } // ctor

} // class SearchRequest
