package pgrid.service.corba.storage;

/**
* pgrid/service/corba/storage/StorageHandleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/demo_pgrid_corba.idl
* Παρασκευή, 5 Οκτώβριος 2012 7:51:04 μμ EEST
*/

public final class StorageHandleHolder implements org.omg.CORBA.portable.Streamable
{
  public pgrid.service.corba.storage.StorageHandle value = null;

  public StorageHandleHolder ()
  {
  }

  public StorageHandleHolder (pgrid.service.corba.storage.StorageHandle initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = pgrid.service.corba.storage.StorageHandleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    pgrid.service.corba.storage.StorageHandleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return pgrid.service.corba.storage.StorageHandleHelper.type ();
  }

}
