package pgrid.service.corba.storage;


/**
* pgrid/service/corba/storage/StorageHandleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from resources/demo_pgrid_corba.idl
* Παρασκευή, 5 Οκτώβριος 2012 7:51:04 μμ EEST
*/

public interface StorageHandleOperations 
{
  pgrid.service.corba.storage.SearchResponse search (pgrid.service.corba.storage.SearchRequest request);
} // interface StorageHandleOperations
